version: "3.8"

services:
  postgres:
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=salon
    build:
      context: database/
      dockerfile: Dockerfile
    ports:
      - 5432:5432
